repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.11  # заменяй на актуальную версию ruff
    hooks:
      - id: ruff
        args: [--fix]  # автоматически исправлять возможное
